# Generated by Django 4.0.3 on 2022-06-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_note_contact_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='note',
        ),
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
    ]
